### ISSUE TITLE
[Feature request] Add overtime for goal tasks

### ISSUE THREAD

**Issue by gavr123456789** [Elnee/Tracky#3]
Yesterday I was working on a task for which I assigned goal 30 minutes, but this time was not enough and I had to create a new task without a time limit.  
It would be cool if goal tasks just started adding time to a some kind of overtime field when the main time was over.  
![image](https://user-images.githubusercontent.com/30507409/71865633-762d2b00-3114-11ea-8475-f9cd94ccc89f.png)

**Comment by Elnee** [comment]
Seems like pretty necessary feature. Thank you for advice!
I'll take this into account.

**Comment by Elnee** [comment]
Future request accomplished by the merge https://github.com/Elnee/Tracky/commit/19ce064bb5e383af8aded3f597126c9f3db961af
I will be very grateful if you test that and leave feedback.
If everything OK you can close issue.

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/75122540-8478db80-56af-11ea-8099-40ee26678988.png)
