### ISSUE TITLE
[Bag] A scrollbar appears in the task creation window

### ISSUE THREAD

**Issue by gavr123456789** [Elnee/Tracky#4]
![image](https://user-images.githubusercontent.com/30507409/72216487-8e48e400-3532-11ea-8983-9dcf3bb69119.png)
![image](https://user-images.githubusercontent.com/30507409/72216489-94d75b80-3532-11ea-993b-7da6c3796057.png)
If there are a lot of tasks and the main window begins to scroll. Then task creation window will also scroll.

**Comment by Elnee** [comment]
Resolved by merge commit https://github.com/Elnee/Tracky/commit/dffdc1945b3967fb94963404859485a8e05a61fe
